name: performancebasedbenefits.com
favicon: null
layout_spectrum: 0.86227
typography_spectrum: 0.5844876163173467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f37337'
    - '#ffffff'
    - '#d5d5d5'
    - '#aaaaaa'
    - '#fac3a9'
  brandStrength: 0.0625
  lightness: 0.8339534534607083
  saturation: 0.5805911575444043
  rhythmicContrast: 0.20129386521875858
purpose: []
